root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
  tsconfigRootDir: __dirname
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - only-warn
rules:
  prefer-const: off
  "@typescript-eslint/no-unused-vars": off
  react-hooks/exhaustive-deps:
    - warn
  quotes: warn
  default-case: warn
  require-await: warn
  "@typescript-eslint/unbound-method": off
  "@typescript-eslint/no-misused-promises":
    - warn
    - checksVoidReturn:
        attributes: false
settings:
  react:
    version: detect
