name: Deploy Site

on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  pull_request: {}

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history.
      - name: Enable Corepack
        run: |
          corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Build
        run: |
          yarn install --immutable
          yarn build
      - name: Setup Index Now
        run: |
          echo "${{ secrets.INDEXNOW_KEY }}" > "./dist/${{ secrets.INDEXNOW_KEY }}.txt"
        if: github.ref_name == 'master'
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

  check-links:
    name: Check Links
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Lychee URL checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --cache
            --verbose
            --no-progress
            --suggest
            --require-https
            --include-fragments
            'dist/**/*.html'
            'dist/**/*.xml'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy-rabbit-edge:
    name: Deploy to Rabbit Edge
    needs:
      - build
      - check-links
    if: github.ref_name == 'master'
    concurrency: rabbit-edge
    environment:
      name: rabbit-edge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Deploy to Bunny Edge
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.3
        with:
          source: "dist"
          destination: ""
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.ACCESS_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"

  index-now:
    name: Update IndexNow
    needs:
      - deploy-rabbit-edge
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: https://silvenga.com/sitemap.xml
          key: ${{ secrets.INDEXNOW_KEY }}
